name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build:
    permissions:
      contents: read        # checkout code
      id-token: write       # nais/docker-build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"

      - name: Install dependencies
        working-directory: ./dokumentasjon
        run: yarn

      - name: Build
        working-directory: ./dokumentasjon
        run: yarn build

      - uses: nais/docker-build-push@v0
        with:
          team: aap
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          image_suffix: ${{ inputs.cluster }}
          tag: ${{ github.sha }}
          context: ./dokumentasjon
  prod:
    permissions:
      contents: read      
      id-token: write     # nais/deploy
    needs: build
    uses: navikt/aap-workflows/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      cluster: prod-gcp
      manifest: dokumentasjon/.nais/nais.yml

