name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build:
    permissions:
      contents: read        # checkout code
      id-token: write       # nais/docker-build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"

      - name: Install dependencies
        working-directory: ./dokumentasjon
        run: yarn

      - name: Build
        working-directory: ./dokumentasjon
        run: yarn build

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker image tag with short sha
        id: dockertag
        run: echo "::set-output name=docker_img::ghcr.io/${{ github.repository }}:$(git rev-parse --short HEAD)"

      - name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./dokumentasjon
          push: true
          tags: ${{ steps.dockertag.outputs.docker_img }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Generate Docker image tag with short sha
        id: dockertag
        run: echo "::set-output name=docker_img::ghcr.io/${{ github.repository }}:$(git rev-parse --short HEAD)"

      - uses: nais/deploy/actions/deploy@v1
        if: github.ref == 'refs/heads/main'
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: ./dokumentasjon/.nais/nais.yml
          IMAGE: ${{ steps.dockertag.outputs.docker_img }}
